/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadButtonFlavorImage: typeof import('./src/components/DownloadButtonFlavorImage.vue')['default']
    DownloadDialog: typeof import('./src/components/DownloadDialog.vue')['default']
    HeroImageSlider: typeof import('./src/components/HeroImageSlider.vue')['default']
    PageSection: typeof import('./src/components/PageSection.vue')['default']
  }
}
